In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jsy/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jsy/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jsy/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jsy/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jsy/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jsy/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jsy/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jsy/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jsy/anaconda3/lib']
    define_macros = [('S

In [4]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
a=np.zeros(10)

In [11]:
a.itemsize

8

In [17]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same pr

In [21]:
z = np.zeros(10)

In [22]:
z[4]=1

In [23]:
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [26]:
z = np.arange(10,20,1)

In [27]:
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
z[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [30]:
z=np.arange(0,9,1)
z.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
z=[1,2,0,0,4,0]
np.nonzero(z)

(array([0, 1, 4]),)

In [35]:
z=np.eye(3,3)

In [36]:
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
a=np.random.random((3,3,3))

In [43]:
a.shape
a

array([[[0.02264872, 0.8878274 , 0.93925441],
        [0.09587054, 0.59923438, 0.69293429],
        [0.1753526 , 0.89738263, 0.48322041]],

       [[0.64088272, 0.81487854, 0.48492775],
        [0.71092331, 0.31898625, 0.62721597],
        [0.49313082, 0.33373548, 0.02815876]],

       [[0.63193216, 0.94222531, 0.61351981],
        [0.56917975, 0.79971426, 0.89267666],
        [0.41553457, 0.94438393, 0.28543829]]])

In [54]:
a=np.random.random((10,10))
a.min()

0.02418028972399544

In [55]:
np.random.random(30).mean()

0.5216072604222224

In [56]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
a[0,:]=1
a[4,:]=1
a[:,0]=1
a[:,4]=1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='edge')
np.info(np.pad)
z

 pad(array, pad_width, mode, **kwargs)

Pads an array.

Parameters
----------
array : array_like of rank N
    Input array
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function
    One of the following string values or a user supplied function.

    'constant'
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the med

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [66]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [68]:
np.tile([[0,1],[1,0]],(5,5))

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [73]:
a=np.random.random((5,5))
a=(a-a.min())/(a.max()-a.min())
a

array([[0.75505185, 0.        , 0.01975653, 0.93105876, 0.13809945],
       [0.17677213, 0.8271572 , 0.57662905, 0.98780962, 0.82564681],
       [1.        , 0.93253942, 0.66852265, 0.88837776, 0.80486296],
       [0.10666777, 0.35185268, 0.779289  , 0.35433865, 0.13701592],
       [0.56331737, 0.03012072, 0.61546438, 0.62423828, 0.5337244 ]])

In [76]:
z=np.dot(np.ones((5,3)),np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [79]:
z=np.arange(11)
z[(z>3)&(z<8)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [80]:
print(sum(range(5),-1))

9


In [81]:
z=np.arange(5)
z

array([0, 1, 2, 3, 4])

In [82]:
z<<2

array([ 0,  4,  8, 12, 16])

In [83]:
z<-z

array([False, False, False, False, False])

In [84]:
np.array(0) / np.array(0)

/Users/jsy/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [85]:
np.array(0) // np.array(0)

/Users/jsy/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [86]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [101]:
np.datetime64('today')
np.arange(dtype=datetime64['D'])

NameError: name 'datetime64' is not defined

In [102]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
